### ISSUE TITLE
Keys wont be given to player when spawning in truck

### ISSUE THREAD

**Issue by Crazy-tech458** [AgentofDeath/AOD_ElectricJob#1]
Hi, I'm a developer on a server. We recently installed your script however one of the main issues we are having is that when u spawn in the truck for the car it won't give u keys to the vehicle in question.

**Comment by AgentofDeath** [comment]
Default code for QBCore was supported when it was originally written, there was a change in how vehicles spawned in between than.  This hasn't been tested on any recent updates on QBCore, so it would require you to provide more information in regards to what's returning in that key event preventing it, or what's different in your instance.  I ran the code yesterday, and did not receive the same issue.

**Comment by AgentofDeath** [comment]
Closed due to no response.
